name:  Deploy to EC2
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    SSH_USER: ubuntu
    EC2_IP: 51.20.103.28
    APP_FOLDER: ./be_server
    DESTINATION_PATH: /home/ubuntu/be_server
  run: |
    scp -i "${SSH_PRIVATE_KEY}" -r "${APP_FOLDER}" "${SSH_USER}@${EC2_IP}:${DESTINATION_PATH}"
    ssh -i "${SSH_PRIVATE_KEY}" "${SSH_USER}@${EC2_IP}" 'bash -s' < deploy.sh